# Generated by Django 4.2.21 on 2025-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dhan_access_token',
            field=models.TextField(blank=True, help_text='Dhan Access Token', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dhan_access_token_expiry',
            field=models.DateTimeField(blank=True, help_text='Dhan Access Token expiry date', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dhan_client_id',
            field=models.CharField(blank=True, help_text='Dhan Client ID', max_length=200, null=True),
        ),
    ]
