# Generated by Django 4.2.21 on 2025-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dhan_access_token_user_dhan_access_token_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True, help_text='The date and time this account was created.'),
        ),
    ]
