# Generated by Django 4.2.21 on 2025-07-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time this account was created.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dhan_access_token_expiry',
            field=models.DateField(blank=True, help_text='Dhan Access Token expiry date', null=True),
        ),
    ]
