# Generated by Django 4.2.21 on 2025-07-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='risk_per_trade',
            field=models.IntegerField(choices=[(500, '₹500'), (1000, '₹1,000'), (2000, '₹2,000'), (5000, '₹5,000')], default=500, help_text='Maximum capital risk per trade. Used to calculate position size.'),
        ),
    ]
