# Generated by Django 4.2.21 on 2025-07-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_risk_per_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trading_enabled',
            field=models.BooleanField(default=True, help_text='Trade using this account.'),
        ),
    ]
