# Generated by Django 4.2.21 on 2025-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategystock',
            old_name='reversal_bar_date',
            new_name='reversal_bar1_date',
        ),
        migrations.RenameField(
            model_name='strategystock',
            old_name='reversal_bar_high',
            new_name='reversal_bar1_high',
        ),
        migrations.AddField(
            model_name='strategystock',
            name='reversal_bar2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategystock',
            name='reversal_bar2_high',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
