# Generated by Django 4.2.21 on 2025-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy2', '0002_rename_reversal_bar_date_strategystock_reversal_bar1_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategystock',
            name='reversal_bar_found',
            field=models.BooleanField(default=False),
        ),
    ]
