# Generated by Django 4.2.21 on 2025-09-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy2', '0003_strategystock_reversal_bar_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategystock',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
