# Generated by Django 4.2.21 on 2025-09-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy2', '0004_strategystock_purchased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategystock',
            old_name='purchased',
            new_name='is_purchased',
        ),
    ]
