# Generated by Django 4.2.21 on 2025-05-24 16:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text="Ticker symbol, e.g. 'TCS'", max_length=20)),
                ('security_id', models.CharField(help_text='DHAN security ID for the symbol', max_length=20)),
                ('start_date', models.DateField(help_text='Date at which the trend line begins')),
                ('angles', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='List of trend-line angles in degrees (e.g. [45,  65])', size=None)),
                ('price_to_bar_ratio', models.FloatField(help_text='Price-per-bar ratio used to compute the slope')),
                ('start_price', models.DecimalField(decimal_places=4, help_text='Exact close price on start_date', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this TrendLine record was created')),
            ],
        ),
        migrations.CreateModel(
            name='TrendLineCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which the line was checked')),
                ('line_price', models.DecimalField(decimal_places=4, help_text='The trend-line price on this date', max_digits=20)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=4, help_text='The actual market close on this date', max_digits=20, null=True)),
                ('touched', models.BooleanField(default=False, help_text='Whether the actual price touched the trend line')),
                ('checked_at', models.DateTimeField(auto_now_add=True, help_text='When this check was performed')),
                ('trend_line', models.ForeignKey(help_text='The TrendLine being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='market.trendline')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('trend_line', 'date')},
            },
        ),
    ]
