# Generated by Django 4.2.21 on 2025-05-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendline',
            name='line_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
