# Generated by Django 4.2.21 on 2025-07-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendline',
            name='price_to_bar_ratio',
            field=models.DecimalField(decimal_places=4, help_text='Price-per-bar ratio used to compute the slope', max_digits=20),
        ),
    ]
