# Generated by Django 4.2.21 on 2025-05-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_trendline_line_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendline',
            name='angles',
            field=models.JSONField(blank=True, help_text='List of trend-line angles in degrees (e.g. [45,  65])', null=True),
        ),
    ]
