# Generated by Django 4.2.21 on 2025-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_trendline_price_to_bar_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendline',
            name='security_id',
            field=models.CharField(help_text='DHAN security ID for the symbol', max_length=200),
        ),
        migrations.AlterField(
            model_name='trendline',
            name='symbol',
            field=models.CharField(help_text="Ticker symbol, e.g. 'TCS'", max_length=200),
        ),
    ]
