# Generated by Django 4.2.21 on 2025-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_trendline_security_id_alter_trendline_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendlinecheck',
            name='buy_above_high_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The actual price of cross over candle high', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='trendlinecheck',
            name='cross_over_ema',
            field=models.BooleanField(default=False, help_text='Whether the EMA cross over happened'),
        ),
        migrations.AddField(
            model_name='trendlinecheck',
            name='stop_loss_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Stop Loss price sell stock when reached this price', max_digits=20, null=True),
        ),
    ]
