# Generated by Django 4.2.21 on 2025-06-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_trendline_angles'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendlinecheck',
            name='purchased',
            field=models.BooleanField(default=False, help_text='Whether the actual price purchased the trend line'),
        ),
    ]
