# Generated by Django 4.2.21 on 2025-07-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_trendlinecheck_buy_above_high_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendlinecheck',
            name='sold',
            field=models.BooleanField(default=False, help_text='Whether the stock was sold'),
        ),
    ]
