# Generated by Django 4.2.21 on 2025-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_trendlinecheck_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendline',
            name='price_to_bar_ratio',
            field=models.IntegerField(help_text='Price-per-bar ratio used to compute the slope'),
        ),
    ]
