# Generated by Django 4.2.21 on 2025-07-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_trendlinecheck_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendlinecheck',
            name='purchase_qty',
            field=models.IntegerField(blank=True, help_text='The actual qty bought', null=True),
        ),
    ]
