# Generated by Django 4.2.21 on 2025-07-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_trendlinecheck_purchase_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendline',
            name='percent_diff_updated_date',
            field=models.DateField(blank=True, help_text='Date of last update for percent difference', null=True),
        ),
        migrations.AddField(
            model_name='trendline',
            name='percent_difference_cached',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cached % difference from latest valid trading day', max_digits=10, null=True),
        ),
    ]
