# Generated by Django 4.2.21 on 2025-08-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_trendline_percent_diff_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendline',
            options={'verbose_name': 'Trend Line', 'verbose_name_plural': 'Trend Lines'},
        ),
        migrations.AlterUniqueTogether(
            name='trendline',
            unique_together={('symbol', 'start_date', 'angles')},
        ),
    ]
