# Generated by Django 4.2.21 on 2025-08-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_trendline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendlinecheck',
            name='ema5_ever_below_ema25',
            field=models.BooleanField(default=False),
        ),
    ]
