# Generated by Django 4.2.21 on 2025-07-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VibrationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vibration_point_value', models.DecimalField(decimal_places=2, help_text='% buffer/allowance for buy signals', max_digits=5)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='When this value was last updated')),
            ],
        ),
    ]
