# Generated by Django 4.2.21 on 2025-07-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0002_emasetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EMASetting',
            new_name='DEMASetting',
        ),
    ]
