# Generated by Django 4.2.21 on 2025-07-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0003_rename_emasetting_demasetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vibrationpoint',
            name='vibration_point_value',
            field=models.DecimalField(decimal_places=5, help_text='% buffer/allowance for buy signals', max_digits=5),
        ),
    ]
