# Generated by Django 4.2.21 on 2025-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0005_alter_vibrationpoint_vibration_point_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMASetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fast_span', models.PositiveIntegerField(help_text='Fast EMA span (e.g. 5)')),
                ('slow_span', models.PositiveIntegerField(help_text='Slow EMA span (e.g. 26)')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fast_span'],
                'unique_together': {('fast_span', 'slow_span')},
            },
        ),
        migrations.DeleteModel(
            name='DEMASetting',
        ),
    ]
